version: '3'
services:
  db:
    image: mariadb
    container_name: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
#  app:
#    container_name: knesset
#    build: .
#    ports:
#      - '3000:3000'
#    environment:
#      DB_HOST: db
#      DB_USER: root
#      DB_PASSWORD: my-secret-pw
#    links:
#      - db
#    volumes:
#      - .:/app/
